# Generated by Django 5.2.5 on 2025-09-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('own', 'Собственный товар'), ('dropshipping', 'Дропшиппинг')], default='own', max_length=20),
        ),
    ]
