# Generated by Django 5.2.5 on 2025-09-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='competitor_url',
            field=models.URLField(blank=True, help_text='Ссылка на сайт конкурента', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_url',
            field=models.URLField(blank=True, help_text='Ссылка на сайт поставщика', null=True),
        ),
    ]
