# Generated by Django 5.2.5 on 2025-09-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_competitor_url_product_supplier_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='competitor_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена у конкурента', max_digits=10, null=True),
        ),
    ]
