# Generated by Django 5.2.5 on 2025-09-06 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_saleitem_bundle_alter_saleitem_product_bundleitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleBundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.bundle')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='store.sale')),
            ],
        ),
    ]
